services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    user: "$PUID:$PGID"
    depends_on:
      - prometheus
    networks:
      - homenet
    ports:
      - '$GRAFANA_PORT:3000'
    volumes:
      - $DOCKERDIR/appdata/grafana:/var/lib/grafana