services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - gluetun-arr
    network_mode: "service:gluetun-arr"
    volumes:
      - $DOCKERDIR/appdata/jackett:/config
      - $TORRENTDIR:/blackhole
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
