services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - homenet
    depends_on:
      - mariadb
    ports:
      - "$PHPMYADMIN_PORT:80"
    environment:
      - PMA_HOST=$SERVERIP_LOCAL
      - PMA_PORT=$MARIADB_PORT
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
