services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    depends_on:
      - gluetun-arr
    network_mode: "service:gluetun-arr"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DOWNLOADDIR:/downloads
      - $DOWNLOADDIR:/data/completed
      - $MOVIESDIR:/movies
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
