services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - homenet
    ports:
      - "$STIRLING_PORT:8080"
    volumes:
      - $DOCKERDIR/appdata/stirling/trainingData:/usr/share/tessdata
      - $DOCKERDIR/appdata/stirling/extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=no_NB